<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 *  Implements hook_help().
 */
function hello_world_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name){
    case 'help.page.hello_world':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hello_world_theme() {
  return [
    'hello_world_salutation_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
